FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:latest

LABEL org.opencontainers.image.source "https://github.com/planet-community/build-system-containers"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get dist-upgrade -y \
    && apt-get install --no-install-recommends -y libclang-dev \
        llvm-dev clang build-essential g++-multilib \
        libc6-dev-i386 gcc-arm-none-eabi libsdl2-dev libasound2-dev
