FROM ghcr.io/cross-rs/aarch64-linux-android:latest

LABEL org.opencontainers.image.source https://github.com/cosmo-codios/codios-build-containers

ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture arm64 \
    && apt-get update \
    && apt-get install -y pkg-config:amd64 \
	protobuf-compiler:amd64
	protobuf-compiler:arm64
