FROM ghcr.io/cross-rs/aarch64-linux-android:edge

LABEL org.opencontainers.image.source "https://github.com/planet-community/build-system-containers"

ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture arm64 \
    && apt-get update \
    && apt-get install -y pkg-config:amd64 \
	protobuf-compiler:amd64
