FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:edge

LABEL org.opencontainers.image.source https://github.com/cosmo-codios/codios-build-containers

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y libdbus-1-dev:amd64 \
       pkg-config:amd64 libudev-dev:amd64 libglib2.0-dev:amd64 \
       libudev-dev:amd64 libdbus-1-dev:amd64 libclang-dev:amd64 \
       libsdl2-dev:amd64 cmake:amd64 libsqlite3-dev:amd64 \
       pkg-config:amd64 protobuf-compiler
